version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - quiz_db
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - BUNDLE_GEMFILE=/app/Gemfile
      - BUNDLE_ENV=development
  quiz_db:
    image: postgres:12.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=quiz_builder
      - POSTGRES_PASSWORD=quiz_builder
      - POSTGRES_DB=quiz_builder
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  bundler_gems:
  db:
    driver: local



